In [ ]:
from google.colab import drive, files
drive.mount('/content/gdrive/')

import os
PROJECT_FOLDER = "/content/gdrive/MyDrive/Colab Notebooks/Thesis"
os.chdir(PROJECT_FOLDER)
print("Current dir: ", os.getcwd())

Mounted at /content/gdrive/
Current dir:  /content/gdrive/MyDrive/Colab Notebooks/Thesis

In [ ]:
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [ ]:
data = pd.read_csv("AMZN_DATA_WITH_NEWS_NO_SENTIMENT.csv")
data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,article-title
0,2021-05-10,164.115997,164.149994,159.500000,159.524506,116772000,0.0,0.0,"""'Formula One great to develop electric vans, ..."
1,2021-05-11,156.813995,161.899994,156.368500,161.195496,92396000,0.0,0.0,"""'Washington Post names Sally Buzbee first wom..."
2,2021-05-12,159.250000,160.397003,156.654999,157.597000,98728000,0.0,0.0,"""'Sonos boosts sales outlook despite global ch..."
3,2021-05-13,159.273499,160.192001,156.649994,158.073502,67018000,0.0,0.0,"""'Amazon seeks renewable power for Japan data ..."
4,2021-05-14,159.278000,161.442993,159.149994,161.145004,66500000,0.0,0.0,"""'Less than 3% of U.S. small businesses could ..."

In [ ]:
nltk.download('vader_lexicon')

stock_sentiment = {
    'surges': 15,
    'rallies': 12,
    'beats': 10,
    'climbs': 8,
    'tops': 6,
    'misses': -8,
    'drops': -10,
    'plunges': -20,
    'warns': -15,
    'crashes': -25,
}

vader = SentimentIntensityAnalyzer()
vader.lexicon.update(stock_sentiment)

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

In [ ]:
scores = [vader.polarity_scores (titles) for titles in data['article-title'].values]

In [ ]:
scores_df = pd.DataFrame(scores)
data = pd.concat([data, scores_df], axis = 1)

In [ ]:
data.head(50)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,article-title,neg,neu,pos,compound
0,2021-05-10,164.115997,164.149994,159.500000,159.524506,116772000,0.0,0.0,"""'Formula One great to develop electric vans, ...",0.000,0.923,0.077,0.8850
1,2021-05-11,156.813995,161.899994,156.368500,161.195496,92396000,0.0,0.0,"""'Washington Post names Sally Buzbee first wom...",0.067,0.889,0.044,-0.7430
2,2021-05-12,159.250000,160.397003,156.654999,157.597000,98728000,0.0,0.0,"""'Sonos boosts sales outlook despite global ch...",0.065,0.829,0.106,0.8449
3,2021-05-13,159.273499,160.192001,156.649994,158.073502,67018000,0.0,0.0,"""'Amazon seeks renewable power for Japan data ...",0.017,0.855,0.128,0.9501
4,2021-05-14,159.278000,161.442993,159.149994,161.145004,66500000,0.0,0.0,"""'Less than 3% of U.S. small businesses could ...",0.014,0.914,0.072,0.9008
5,2021-05-17,162.296494,164.637497,161.729507,163.519501,74478000,0.0,0.0,"""'EU eyes another go at more unified European ...",0.061,0.808,0.131,0.9752
6,2021-05-18,164.628998,165.600006,161.518494,161.613998,56568000,0.0,0.0,"""'Amazon extends moratorium on police use of f...",0.043,0.876,0.081,0.9022
7,2021-05-19,159.750000,161.737503,159.199997,161.589996,53594000,0.0,0.0,"""'Amazon.com faces five new racial, gender bia...",0.065,0.913,0.022,-0.6808
8,2021-05-20,162.220001,162.983994,161.809006,162.384003,52664000,0.0,0.0,"""'S&P 500 Snaps 3-Day Losing Streak as Tech Re...",0.030,0.822,0.148,0.9726
9,2021-05-21,162.500000,162.834503,159.850494,160.154007,82098000,0.0,0.0,"""'U.S. investors look to Europe for next leg o...",0.025,0.876,0.099,0.9001
10,2021-05-24,160.774994,162.897507,160.524994,162.249496,48456000,0.0,0.0,"""'S&P 500 Jumps as Tech Flexes MusclesBy Yasin...",0.052,0.948,0.000,-0.5423
11,2021-05-25,163.333496,163.990997,160.688004,162.952499,65222000,0.0,0.0,"'""District of Columbia accuses Amazon of unfai...",0.056,0.808,0.136,0.9738
12,2021-05-26,163.729507,164.786499,162.925507,163.257996,47680000,0.0,0.0,"'""Analysis-Amazon\'s Washington critics set to...",0.016,0.864,0.121,0.9850
13,2021-05-27,162.800003,163.018005,161.501999,161.505493,51224000,0.0,0.0,"""'Amazon.com vs. Walmart: Which E-commerce Sto...",0.026,0.925,0.048,0.3094
14,2021-05-28,162.100006,162.399506,160.985001,161.153503,46596000,0.0,0.0,"""'Amazon pressed for racial equity review afte...",0.000,0.851,0.149,0.9351
15,2021-06-01,162.175003,162.548996,160.453003,160.932495,48600000,0.0,0.0,"""'Ecuador launches 100-day vaccine plan, presi...",0.036,0.864,0.100,0.8402
16,2021-06-02,161.154999,161.750000,160.399994,161.699493,40290000,0.0,0.0,"'""U.S. Treasury says G7 expected to endorse U....",0.090,0.812,0.098,-0.8481
17,2021-06-03,160.211502,160.722000,159.201508,159.350494,47966000,0.0,0.0,"""'Dow Closes Flat as Traders Await Jobs Friday...",0.034,0.897,0.069,0.7930
18,2021-06-04,160.600006,161.050003,159.940506,160.311005,44994000,0.0,0.0,"'""Exclusive: Biden\'s electric vehicle plan in...",0.011,0.890,0.099,0.9764
19,2021-06-07,159.866501,160.399994,158.610001,159.900497,44316000,0.0,0.0,"'""Big tech supports global tax, but wants digi...",0.064,0.803,0.133,0.9937
20,2021-06-08,161.130493,163.976501,160.900497,163.205505,68334000,0.0,0.0,"""'Amazon reviewing bids to replace JPMorgan as...",0.047,0.872,0.081,0.8591
21,2021-06-09,163.643494,164.878998,163.535004,164.057495,49110000,0.0,0.0,"""'Dish Drops on JPMorgan DowngradeBy Christian...",0.079,0.855,0.066,-0.7906
22,2021-06-10,164.100494,167.550003,164.057495,167.482498,69530000,0.0,0.0,"'""GameStop falls 27% on potential share sale, ...",0.038,0.884,0.078,0.8689
23,2021-06-11,167.482498,168.328995,166.672501,167.341507,56348000,0.0,0.0,"'""White House says G7 leaders will endorse pro...",0.012,0.925,0.063,0.9201
24,2021-06-14,167.341507,169.250000,166.774994,169.193497,51394000,0.0,0.0,"'""3 Large-Cap Tech Stocks Wall Street Predicts...",0.000,0.934,0.066,0.5719
25,2021-06-15,169.199997,169.849503,168.155502,169.156494,48524000,0.0,0.0,"'""Cloud ramp up weighs on Oracle\'s profit vie...",0.017,0.884,0.099,0.9682
26,2021-06-16,169.600006,171.317505,168.026505,170.762497,84056000,0.0,0.0,"'""Apple\'s Cook says proposed EU tech rules th...",0.027,0.902,0.072,0.5267
27,2021-06-17,170.158997,174.860001,170.050003,174.462006,102730000,0.0,0.0,"""'U.S. House panel to vote Wednesday on bills ...",0.092,0.873,0.035,-0.7783
28,2021-06-18,173.999496,175.350006,173.685501,174.345001,104954000,0.0,0.0,'\'Facebook\\\'s \\\'Neighborhoods\\\' faces c...,0.000,0.890,0.110,0.8316
29,2021-06-21,173.820999,174.100006,171.699997,172.697998,65542000,0.0,0.0,"""'India plans tighter e-commerce rules amid co...",0.047,0.881,0.072,0.7920
30,2021-06-22,172.903000,176.188995,172.804504,175.272003,66902000,0.0,0.0,"""'India e-commerce rules cast cloud over Amazo...",0.031,0.873,0.096,0.9387
31,2021-06-23,175.250000,176.050003,174.160004,175.190994,56266000,0.0,0.0,"""'U.S. House panel still to vote on data porta...",0.011,0.950,0.039,0.4588
32,2021-06-24,175.382004,176.242996,171.542496,172.453995,76640000,0.0,0.0,"'""U.S. panel votes yes on \'break \'em up\' an...",0.031,0.880,0.089,0.9246
33,2021-06-25,173.199997,173.240997,169.709000,170.072998,78820000,0.0,0.0,"'""Amazon\'s AWS buys message encrypting servic...",0.028,0.868,0.104,0.8807
34,2021-06-28,170.800003,172.399994,170.675507,172.194504,44856000,0.0,0.0,"""'S&P 500, Nasdaq Close at Record on Tech Bets...",0.000,0.968,0.032,0.5267
35,2021-06-29,171.940994,172.801498,171.151505,172.406998,41968000,0.0,0.0,"""'Musk touts Starlink progress as cost, demand...",0.011,0.905,0.083,0.9371
36,2021-06-30,172.052994,173.580002,171.750000,172.007996,48080000,0.0,0.0,"""'S&P 500 Hits Record High as Cyclical Stocks ...",0.021,0.921,0.058,0.7003
37,2021-07-01,171.730499,172.850006,170.470993,171.648499,40742000,0.0,0.0,"'""Trailblazing female pilot will go to space a...",0.022,0.862,0.115,0.9638
38,2021-07-02,172.582001,175.585999,171.845993,175.548996,63388000,0.0,0.0,"""'Amazon to grant new CEO Jassy over $200 mill...",0.043,0.909,0.048,0.2023
39,2021-07-06,176.505493,184.274002,176.449997,183.787003,134896000,0.0,0.0,"'""The fight by Microsoft and Amazon for the Pe...",0.105,0.816,0.078,-0.7900
40,2021-07-07,185.869003,186.710007,183.945496,184.828995,106562000,0.0,0.0,"""'Factbox-Bezos, Branson and Musk: Who is winn...",0.018,0.918,0.064,0.8779
41,2021-07-08,182.177994,187.999496,181.056000,186.570496,103612000,0.0,0.0,"""'Exclusive: Online payments firm Stripe takes...",0.037,0.888,0.075,0.8199
42,2021-07-09,186.126007,187.399994,184.669998,185.966995,74964000,0.0,0.0,"'""FTC extends probe of Amazon, MGM deal - sour...",0.033,0.873,0.094,0.8442
43,2021-07-12,187.199997,187.864502,184.839493,185.927505,51432000,0.0,0.0,"""'Virgin Galactic files for $500 million stock...",0.020,0.888,0.092,0.9847
44,2021-07-13,185.104996,188.654007,183.565994,183.867996,76918000,0.0,0.0,"""'Biden nominates surgeon, author Atul Gawande...",0.042,0.914,0.045,-0.0387
45,2021-07-14,185.442505,185.882996,183.041504,184.084000,65932000,0.0,0.0,"'""Toyota buys U.S. mapping, road data firm to ...",0.118,0.868,0.014,-0.9761
46,2021-07-15,184.710007,184.770004,181.046005,181.559998,63706000,0.0,0.0,"""'Asian Stocks Down as COVID-19 Economic Recov...",0.024,0.860,0.116,0.9773
47,2021-07-16,181.665497,182.302994,178.522995,178.681503,80874000,0.0,0.0,"""'S&P 500 Snaps 3-Week Win Streak Despite Upbe...",0.037,0.844,0.119,0.9201
48,2021-07-19,176.628998,177.510498,174.957993,177.479507,75692000,0.0,0.0,"""'Amazon to slow down COVID-19 testing for war...",0.040,0.918,0.043,0.1027
49,2021-07-20,178.365997,179.600006,175.899994,178.659500,65114000,0.0,0.0,"""'Pressure on Big Tech builds as Biden picks a...",0.038,0.813,0.149,0.9674

In [ ]:
data.to_csv("AMZN_VADER_SCORE_READY_FOR_TRAINING.csv")